name: Validate

on:
    push:
        branches: ['main']
    pull_request:
        branches-ignore: ['dependabot/**']
    workflow_dispatch:
    schedule:
        # schedule weekly tests, since some dependencies are not intended to be pinned
        # this means: at 23:42 on Fridays
        - cron: '42 23 * * 5'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    OPEN_API_GENERATOR_VERSION: 'v7.3.0'

jobs:
    generate-library-code:
        name: Generate Library Code ${{ matrix.language }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                language: ['go', 'typescript']
        steps:
            - name: Checkout
              # see https://github.com/actions/checkout
              uses: actions/checkout@v4
            - name: Run OpenAPI Generator
              uses: addnab/docker-run-action@v3
              with:
                  image: openapitools/openapi-generator-cli:${{ env.OPEN_API_GENERATOR_VERSION }}
                  options: -v ${{ github.workspace }}:/local
                  run: /usr/local/bin/docker-entrypoint.sh batch --clean /local/${{ matrix.language }}.yaml
            - name: Check Generation
              run: ls -alR ${{ github.workspace }}/out
